# -*- coding: utf-8 -*-
"""НикитаСорокинЗадача1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjKbXdHDV8pAVdJlfof46Ily2eAeDivT
"""

# Задача 1 "even or odd"
# https://www.codewars.com/kata/53da3dbb4a5168369a0000fe/train/python

def even_or_odd(a):
  return "Even" if a % 2 == 0 else "Odd"