# -*- coding: utf-8 -*-
"""НикитаСорокинЗадача2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HjKbXdHDV8pAVdJlfof46Ily2eAeDivT
"""

# Задача 2 "simple_multiplication"
# https://www.codewars.com/kata/583710ccaa6717322c000105/train/python

def simple_multiplication(a):
  return a * 8 if a % 2 == 0 else a * 9